import { Command } from "commander";
import { sendIpcCommand } from "./utils/ipc";
import { getPublicIP } from "./utils/networking";
import { validateEnvironment } from "./utils/misc";
import { logsCommandHandler, serviceLogsCommandHandler } from "./cli/logs";

validateEnvironment();

const program = new Command()
	.name("paas")
	.description("CLI for managing a PaaS cluster.");

program
	.command("create")
	.description("Used to initialize a new cluster, creating the initial coordinator node.")
	.option("--node-ip <ip>", "The IP that other nodes can reach this node at. Defaults to the IP used for outgoing connections.")
	.action(async (options: { nodeIp?: string }) => {
		await sendIpcCommand("create", { nodeIp: options.nodeIp ?? (await getPublicIP()) });
	});

program
	.command("accept")
	.description("Used to start listening for join requests to allow nodes to join the cluster.")
	.action(async () => {
		await sendIpcCommand("accept", {});
	});

program
	.command("join")
	.description("Used to join the node to an existing cluster.")
	.argument("<bundle-json>", "The JSON bundle generated by the coordinator node when accepting join requests.")
	.action(async (bundleJson: string) => {
		await sendIpcCommand("join", bundleJson);
	});

program
	.command("kick")
	.description("Removes a node from the cluster.")
	.argument("<node-id>", "The ID of the node to remove.")
	.action(async (nodeId: string) => {
		const parsedNodeId = Number.parseInt(nodeId, 10);
		if (!Number.isInteger(parsedNodeId) || parsedNodeId < 1 || parsedNodeId > 255) {
			throw new Error("Node ID must be an integer between 1 and 255.");
		}

		await sendIpcCommand("kick", { nodeId: parsedNodeId });
	});

program
	.command("remove")
	.description("Removes a desired service deployment from cluster config.")
	.argument("<id>", "The ID of the service to remove.")
	.action(async (id: string) => {
		await sendIpcCommand("remove", { id });
	});

program
	.command("config")
	.description("Displays the current cluster configuration.")
	.action(async () => {
		await sendIpcCommand("config", {});
	});

program
	.command("status")
	.description("Displays the current cluster node statuses.")
	.action(async () => {
		await sendIpcCommand("status", {});
	});

program
	.command("reelect")
	.description("Requests a new leader election.")
	.action(async () => {
		await sendIpcCommand("reelect", {});
	});

program
	.command("logs")
	.description("Stream the daemon or service logs to the console.")
	.argument("[service-id]", "The ID of the service to show Docker logs for.")
	.action(async (serviceId?: string) => {
		if (serviceId) {
			await serviceLogsCommandHandler(serviceId);
			return;
		}

		await logsCommandHandler();
	});

const deployCommand = program.command("deploy").description("Adds or updates desired service deployments in cluster config.");

function parseEnv(value: string, previous: Record<string, string> = {}): Record<string, string> {
	const index = value.indexOf("=");
	if (index <= 0) throw new Error("Environment variables entered as KEY=VALUE.");

	return {
		...previous,
		[value.slice(0, index)]: value.slice(index + 1),
	};
}

deployCommand
	.command("web")
	.description("Adds or updates a stateless web app deployment.")
	.argument("<id>", "A unique identifier string for the web service.")
	.argument("<image>", "The container image to deploy.")
	.argument("<domain>", "The domain to route incoming traffic for this service.")
	.argument("<internal-port>", "The port that the service listens on inside the container.")
	.option("--env <KEY=VALUE>", "Set an environment variable.", parseEnv, {})
	.option("--health-path <path>", "A HTTP path used by HAProxy to check the health of the service to better react to failures. Must start with a '/'.")
	.action(async (id: string, image: string, domain: string, internalPort: string, options: { env: Record<string, string>; healthPath?: string }) => {
		const parsedPort = Number.parseInt(internalPort, 10);
		if (!Number.isInteger(parsedPort) || parsedPort <= 0) {
			throw new Error("Internal port must be a positive integer.");
		}

		await sendIpcCommand("deploy", {
			type: "web",
			id,
			image,
			domain,
			internalPort: parsedPort,
			env: options.env,
			healthPath: options.healthPath,
		});
	});

deployCommand
	.command("patroni")
	.description("Adds or updates a Patroni PostgreSQL deployment.")
	.argument("<id>", "A unique identifier string for the PostgreSQL service.")
	.option("--sync-mode <mode>", "Replication mode for the PostgreSQL service: async or sync.", "async")
	.action(async (id: string, options: { syncMode: string }) => {
		await sendIpcCommand("deploy", {
			type: "patroni",
			id,
			syncMode: options.syncMode,
		});
	});

program.parseAsync();
