import { Command } from "commander";
import { sendIpcCommand } from "./utils/ipc";
import { getPublicIP } from "./utils/ip";

const program = new Command();

program
	.command("create")
	.description("Used to initialize a new cluster, creating the initial coordinator node.")
	.option("--node-ip <ip>", "The IP that other nodes can reach this node at. Defaults to the IP used for outgoing connections.")
	.action(async (options: { nodeIp?: string }) => {
		await sendIpcCommand("create", { nodeIp: options.nodeIp ?? (await getPublicIP()) });
	});

program
	.command("accept")
	.description("Used to start listening for join requests to allow nodes to join the cluster.")
	.action(async () => {
		await sendIpcCommand("accept", {});
	});

program
	.command("join")
	.description("Used to join the node to an existing cluster.")
	.argument("<bundle-json>", "The JSON bundle generated by the coordinator node when accepting join requests.")
	.action(async (bundleJson: string) => {
		await sendIpcCommand("join", bundleJson);
	});

void program.parseAsync();
