import { Command } from "commander";
import { sendIpcCommand } from "./utils/ipc";
import { getPublicIP } from "./utils/ip";

const program = new Command();

program
	.command("create")
	.description("Used to initialize a new cluster, creating the initial coordinator node.")
	.option("--node-ip <ip>", "The IP that other nodes can reach this node at. Defaults to the IP used for outgoing connections.")
	.action(async (options: { nodeIp?: string }) => {
		await sendIpcCommand("create", { nodeIp: options.nodeIp ?? (await getPublicIP()) });
	});

program
	.command("accept")
	.description("Used to start listening for join requests to allow nodes to join the cluster.")
	.action(async () => {
		await sendIpcCommand("accept", {});
	});

program
	.command("join")
	.description("Used to join the node to an existing cluster.")
	.argument("<bundle-json>", "The JSON bundle generated by the coordinator node when accepting join requests.")
	.action(async (bundleJson: string) => {
		await sendIpcCommand("join", bundleJson);
	});

program
	.command("config")
	.description("Displays the current cluster configuration.")
	.action(async () => {
		await sendIpcCommand("config", {});
	});

const deployCommand = program.command("deploy").description("Adds or updates desired service deployments in cluster config.");

deployCommand
	.command("web")
	.description("Adds or updates a stateless web app deployment.")
	.argument("<id>", "A unique identifier string for the web service.")
	.argument("<image>", "The container image to deploy.")
	.argument("<domain>", "The domain to route incoming traffic for this service.")
	.argument("<internal-port>", "The port that the service listens on inside the container.")
	.action(async (id: string, image: string, domain: string, internalPort: string) => {
		const parsedPort = Number.parseInt(internalPort, 10);
		if (!Number.isInteger(parsedPort) || parsedPort <= 0) {
			throw new Error("Internal port must be a positive integer.");
		}

		await sendIpcCommand("deploy", {
			type: "web",
			id,
			image,
			domain,
			internalPort: parsedPort,
		});
	});

deployCommand
	.command("patroni")
	.description("Adds or updates a Patroni PostgreSQL deployment.")
	.argument("<id>", "A unique identifier string for the PostgreSQL service.")
	.option("--sync-mode <mode>", "Replication mode for the PostgreSQL service: async or sync.", "async")
	.action(async (id: string, options: { syncMode: string }) => {
		await sendIpcCommand("deploy", {
			type: "patroni",
			id,
			syncMode: options.syncMode,
		});
	});

void program.parseAsync();
